/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.creacionescaleb.view.subpaginas;

import com.mycompany.creacionescaleb.dao.DaoUsuario;
import com.mycompany.creacionescaleb.dao.impl.DaoUsuarioImpl;
import com.mycompany.creacionescaleb.entidades.Usuario;
import com.mycompany.creacionescaleb.util.CodificarDecoficarBase64;
import java.awt.Color;
import java.awt.Image;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class PerfilJPanel extends javax.swing.JPanel {

    /**
     * Creates new form PerfilJPanel
     */
    private Usuario dataPersona = new Usuario();
    public PerfilJPanel() {
        initComponents();
    }
        
    public PerfilJPanel(Usuario user) {
        initComponents();
        this.dataPersona = user;
        //setCamposInfo();
        setCamposInfo();
        deshabilitarCampos(false);
    }
    
    public void setCamposInfo() {
        Integer id = dataPersona.getId();
        String dni = dataPersona.getDni();
        String nombres = dataPersona.getNombres();
        String paterno = dataPersona.getPaterno();
        String materno = dataPersona.getMaterno();
        String genero = dataPersona.getGenero();
        String feNacimiento = dataPersona.getFeNacimiento();
        String correo = dataPersona.getCorreo();
        String feCreacion = dataPersona.getFeCreacion();
        String tipoUsuario = dataPersona.getTipoUsuario();
        String username = dataPersona.getUsername();
        String password = dataPersona.getPassword();
        
        textDni.setText(dni);
        textNombre.setText(nombres);
        textApePaterno.setText(paterno);
        textApeMaterno.setText(materno);
        textGenero.setText(genero);
        textFeNacimiento1.setText(feNacimiento);
        textCorreo.setText(correo);
        textFeCreacion.setText(feCreacion);
        textTipUser.setText(tipoUsuario);
        textNomUsuario.setText(username);
    }
    
    private void setFotoInLabel(JLabel labelName, String base64Image) {
        byte[] fotoPersona = CodificarDecoficarBase64.decodeImage(base64Image);
        ImageIcon image = new ImageIcon(fotoPersona);
        
        Icon icon = new ImageIcon(
                image.getImage().getScaledInstance(labelName.getWidth(), labelName.getHeight(), Image.SCALE_DEFAULT));
        labelName.setIcon(icon);
        this.repaint();
    }
    
    public void setFotoPersona() {
        setFotoInLabel(fotoEmpleado, dataPersona.getFoto());
    }
    
    private void deshabilitarCampos(boolean stado) {
        textDni.setEnabled(false);
        textNombre.setEnabled(false);
        textApePaterno.setEnabled(false);
        textApeMaterno.setEnabled(false);
        textGenero.setEnabled(false);
        textFeNacimiento1.setEnabled(false);
        textCorreo.setEnabled(stado);
        textFeCreacion.setEnabled(false);
        textTipUser.setEnabled(false);
        textNomUsuario.setEnabled(stado);
        btnCancelar.setEnabled(false);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        textTipUser = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        textNombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        textApePaterno = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        textApeMaterno = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        textGenero = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        textCorreo = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        textNomUsuario = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        textFeCreacion = new javax.swing.JTextField();
        btnEditar = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        textFeNacimiento1 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        textDni = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        fotoEmpleado = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Detalle del Pesonal:  ");

        jLabel2.setText("Tipo de usuario:");

        jLabel3.setText("Nombre:");

        jLabel4.setText("Apellido Paterno:");

        jLabel5.setText("Apellido Materno:");

        jLabel6.setText("Genero:");

        jLabel8.setText("Foto");

        jLabel9.setText("Nombre de usuario:");

        jLabel10.setText("Fecha de creacion:");

        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/user-edit.png"))); // NOI18N
        btnEditar.setText("EDITAR");
        btnEditar.setBorderPainted(false);
        btnEditar.setContentAreaFilled(false);
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        jLabel11.setText("Fecha de Nacimiento:");

        jLabel12.setText("DNI:");

        jLabel13.setText("Correo:");

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/contract.png"))); // NOI18N
        btnCancelar.setText("CANCELAR");
        btnCancelar.setBorderPainted(false);
        btnCancelar.setContentAreaFilled(false);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(textDni, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(textNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(textApePaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textApeMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(textTipUser, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)
                            .addComponent(textFeNacimiento1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13)
                            .addComponent(textCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(textNomUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(80, 80, 80)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fotoEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel6)
                        .addGap(159, 159, 159)
                        .addComponent(jLabel10))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(textGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(textFeCreacion, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(80, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(4, 4, 4)
                        .addComponent(textDni, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(jLabel3)
                        .addGap(4, 4, 4)
                        .addComponent(textNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(jLabel4)
                        .addGap(4, 4, 4)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(textApePaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(textApeMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(4, 4, 4)
                        .addComponent(textTipUser, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(jLabel11)
                        .addGap(4, 4, 4)
                        .addComponent(textFeNacimiento1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(jLabel13)
                        .addGap(4, 4, 4)
                        .addComponent(textCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(jLabel9)
                        .addGap(4, 4, 4)
                        .addComponent(textNomUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(fotoEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jLabel8)))
                .addGap(2, 2, 2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel10))
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFeCreacion, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        String estadoBoton = btnEditar.getText();
        if (estadoBoton.equals("EDITAR")){
            deshabilitarCampos(true);
            btnEditar.setText("GUARDAR");
            btnCancelar.setEnabled(true);
        } else {
            String newCorreo = textCorreo.getText();
            String newUsername = textNomUsuario.getText();
            String isValid = validarDatos();
            if (isValid == null) {
                if (!newCorreo.equals(dataPersona.getCorreo()) || !newUsername.equals(dataPersona.getUsername())) {
                    DaoUsuario dao = new DaoUsuarioImpl();
                    dataPersona.setCorreo(newCorreo);
                    dataPersona.setUsername(newUsername);
                    String update = dao.UsuarioUptdate(dataPersona);
                    if (update==null)
                        JOptionPane.showMessageDialog(this, "Actualizado correctamente.", "AVISO", JOptionPane.INFORMATION_MESSAGE);
                    else
                        JOptionPane.showMessageDialog(this, update, "AVISO", JOptionPane.ERROR_MESSAGE);
                }
                else
                    JOptionPane.showMessageDialog(this, "No se realizo ningun cambio.", "AVISO", JOptionPane.INFORMATION_MESSAGE);
                
                deshabilitarCampos(false);
                btnEditar.setText("EDITAR");
            } else 
                JOptionPane.showMessageDialog(this, isValid, "AVISO", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        textCorreo.setText(dataPersona.getCorreo());
        textNomUsuario.setText(dataPersona.getUsername());
        deshabilitarCampos(false);
        btnEditar.setText("EDITAR");
    }//GEN-LAST:event_btnCancelarActionPerformed
    
    // Validar campo de imputs
    private String validarCorreo(String correo) {
        String regex = "^[a-zA-Z0-9_+&*-]+(?:\\.[a-zA-Z0-9_+&*-]+)*@(?:[a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,7}$";
        Matcher matcher = Pattern.compile(regex).matcher(correo);
        return matcher.matches() ? null : "Correo no es válido";
    }
    
    private String validarNomUsuario(String nomUsuario) {
        String regex = "^[a-zA-Z0-9_]+$";
        Matcher matcher = Pattern.compile(regex).matcher(nomUsuario);
        return matcher.matches() ? null : "Nombre de usuario no es válido";
    }
    
    private String validarDatos() {
        String nombreCorreo, valUserName;
        nombreCorreo = validarCorreo(textCorreo.getText());
        valUserName = validarNomUsuario(textNomUsuario.getText());
        
        if (nombreCorreo == null && valUserName == null) {
            return null;
        } else {
            String errorString = String.format("ERROR: %s%s", nombreCorreo != null ? nombreCorreo + ", " : "", valUserName != null ? valUserName + ", " : "");
            return errorString.substring(0, errorString.length() - 2) + ".";
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEditar;
    public javax.swing.JLabel fotoEmpleado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField textApeMaterno;
    private javax.swing.JTextField textApePaterno;
    private javax.swing.JTextField textCorreo;
    private javax.swing.JTextField textDni;
    private javax.swing.JTextField textFeCreacion;
    private javax.swing.JTextField textFeNacimiento1;
    private javax.swing.JTextField textGenero;
    private javax.swing.JTextField textNomUsuario;
    private javax.swing.JTextField textNombre;
    private javax.swing.JTextField textTipUser;
    // End of variables declaration//GEN-END:variables
}
