/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.creacionescaleb.view.subpaginas;

import com.mycompany.creacionescaleb.dao.DaoProducto;
import com.mycompany.creacionescaleb.dao.impl.DaoProductoImpl;
import com.mycompany.creacionescaleb.entidades.Producto;
import com.mycompany.creacionescaleb.util.CodificarDecoficarBase64;
import com.mycompany.creacionescaleb.view.Dashboard;
import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author USER
 */
public class RegistroInventarioJPanel extends javax.swing.JPanel {

    /**
     * Creates new form RegistroInventarioJPanel
     */
    boolean isEdition = false;
    Producto producto = new Producto();
        
    SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
    
    public RegistroInventarioJPanel() {
        initComponents();
    }

    public RegistroInventarioJPanel(Producto producto) {
        initComponents();
        this.producto = producto;
        isEdition = true;
        editionMode();
    }

    public void editionMode() {
        if (isEdition) {
            jLabel1.setText("Edicion de producto:");
            jButton2.setText("EDITAR");

            jTextField2.setText(producto.getNombre());
            jTextField3.setText(producto.getDescripcion());
            jTextField4.setText(String.valueOf(producto.getPrecio()));
            jTextField5.setText(String.valueOf(producto.getStock()));
            String generoEdit = producto.getGenero();
            switch (generoEdit) {
                case "Hombre" ->
                    jComboBox1.setSelectedIndex(1);
                case "Mujer" ->
                    jComboBox1.setSelectedIndex(2);
                case "Niño" ->
                    jComboBox1.setSelectedIndex(3);
                case "Niña" ->
                    jComboBox1.setSelectedIndex(4);
            }

            String tipoEdit = producto.getTipo();
            switch (tipoEdit) {
                case "Jean" ->
                    jComboBox2.setSelectedIndex(1);
                case "Short" ->
                    jComboBox2.setSelectedIndex(2);
                case "Pitillo" ->
                    jComboBox2.setSelectedIndex(3);
                case "Baggy" ->
                    jComboBox2.setSelectedIndex(4);
            }
            try {
                jDateFecha.setDate(formato.parse(producto.getFechaIngreso()));
            } catch (ParseException e) {
                e.printStackTrace();
            }
            
        }
    }

    public void setImageEdit() {
        setFotoInLabel(jLabel10, producto.getFotoProducto(), null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jDateFecha = new com.toedter.calendar.JDateChooser();
        jButton3 = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Registro de Inventario:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel3.setText("Nombre:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 100, 20));
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 160, 30));

        jLabel4.setText("Descripcion:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 100, 20));
        jPanel1.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 160, 30));

        jLabel5.setText("Precio:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 100, 20));
        jPanel1.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 160, 30));

        jLabel6.setText("Stock:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 100, 20));
        jPanel1.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 160, 30));

        jLabel7.setText("Genero:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 100, 20));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Hombre", "Mujer", "Niño", "Niña" }));
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 160, 30));

        jLabel8.setText("Tipo:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 50, 100, 20));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Jean", "Short", "Pitillo", "Baggy" }));
        jPanel1.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 70, 160, 30));

        jLabel9.setText("Fecha de ingreso:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, 120, 20));

        jButton1.setText("IMAGE ICON");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 170, 160, 30));
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 40, 260, 300));

        jButton2.setText("AGREGAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 380, 160, 50));

        jDateFecha.setBackground(new java.awt.Color(255, 255, 255));
        jDateFecha.setForeground(new java.awt.Color(0, 153, 153));
        jDateFecha.setDateFormatString("dd/MM/yyyy");
        jPanel1.add(jDateFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, 160, 30));

        jButton3.setText("REGRESAR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 380, 140, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 780, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JFileChooser ficAbrirArchivo = new JFileChooser();
        ficAbrirArchivo.setFileFilter(new FileNameExtensionFilter("Buscar imagen de articulo", "jpg", "jpeg", "png"));
        int respuesta = ficAbrirArchivo.showOpenDialog(this);

        if (respuesta == JFileChooser.APPROVE_OPTION) {
            File archivoImagen = ficAbrirArchivo.getSelectedFile();
            try {
                byte[] bytesImagen = convertirArchivoABytes(archivoImagen);
                String iconProductBase64 = CodificarDecoficarBase64.encodeImage(bytesImagen);
                producto.setFotoProducto(iconProductBase64);
                setFotoInLabel(jLabel10, iconProductBase64, null);
            } catch (IOException e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        DaoProducto dao = new DaoProductoImpl();
        String nombre = jTextField2.getText();
        String descripcion = jTextField3.getText();
        double precio = Double.parseDouble(jTextField4.getText());
        int Stock = Integer.parseInt(jTextField5.getText());
        String genero = String.valueOf(jComboBox1.getSelectedItem());
        String tipo = String.valueOf(jComboBox2.getSelectedItem());
        String feIngreso = formato.format(jDateFecha.getDate());

        producto.setNombre(nombre);
        producto.setDescripcion(descripcion);
        producto.setPrecio(precio);
        producto.setStock(Stock);
        producto.setGenero(genero);
        producto.setTipo(tipo);
        producto.setFechaIngreso(feIngreso);

        try {
            String insert;

            if (!isEdition) {
                insert = dao.ProductoInsert(producto);
            } else {
                insert = dao.ProductoUptdate(producto);
            }
            
            System.out.println(insert);
            
            String successMsg = isEdition ? "modificado" : "registrado";

            javax.swing.JOptionPane.showMessageDialog(this, "Producto " + successMsg + " exitosamente.", "AVISO", javax.swing.JOptionPane.INFORMATION_MESSAGE);

            if (!isEdition) {
                jTextField2.setText("");
                jTextField3.setText("");
                jTextField4.setText("");
                jTextField5.setText("");
                jComboBox1.setSelectedIndex(0);
                jComboBox2.setSelectedIndex(0);
                jDateFecha.setDate(null);
                setFotoProducto();
            }
        } catch (Exception e) {
            String errorMsg = isEdition ? "modificar" : "registrar";
            javax.swing.JOptionPane.showMessageDialog(this, "Ocurrió un error al " + errorMsg + " el Producto.", "AVISO", javax.swing.JOptionPane.ERROR_MESSAGE);
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        InventarioJPanel invt = new InventarioJPanel();
        Dashboard.showJPanel(invt);
    }//GEN-LAST:event_jButton3ActionPerformed

    private byte[] convertirArchivoABytes(File archivo) throws IOException {
        FileInputStream fis = new FileInputStream(archivo);
        byte[] bytes = new byte[(int) archivo.length()];
        fis.read(bytes);
        fis.close();
        return bytes;
    }

    private void setFotoInLabel(JLabel labelName, String base64Image, String root) {
        ImageIcon image = null;
        if (root == null) {
            byte[] fotoPersona = CodificarDecoficarBase64.decodeImage(base64Image);
            image = new ImageIcon(fotoPersona);
        } else {
            String fotoPersona = root;
            image = new ImageIcon(fotoPersona);
        }

        Icon icon = new ImageIcon(
                image.getImage().getScaledInstance(labelName.getWidth(), labelName.getHeight(), Image.SCALE_DEFAULT));
        labelName.setIcon(icon);
        this.repaint();
    }

    public void setFotoProducto() {
        String rutaFoto = "src/main/resources/jeans.jpeg";
        setFotoInLabel(jLabel10, null, rutaFoto);
        String imageDefault = CodificarDecoficarBase64.encodeImage(convertImageToBytes(rutaFoto));
        producto.setFotoProducto(imageDefault);
    }

    private static byte[] convertImageToBytes(String imagePath) {
        try {
            Path path = Paths.get(imagePath);
            return Files.readAllBytes(path);
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private com.toedter.calendar.JDateChooser jDateFecha;
    private javax.swing.JLabel jLabel1;
    public static javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
